name: Static Analysis for Python Scripts

on:
  pull_request:
    branches: [ main ]

jobs:
  format-lint:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: format-lint
        environment-file: requirements.txt
        python-version: 3.8
        auto-activate-base: false
    - run: conda info
    - run: conda list
    - name: check formats
      run: make format
    - name: run linters
      run: make lint
